name: meupedido_core
description: Core de MeuPedido APP.
author: Isaias Goncalves <ss.initech@gmail.com>
version: 0.0.1
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  image_cropper: ^1.2.2
  image_picker: ^0.6.6+4
  cached_network_image: ^2.2.0+1
  connectivity: ^0.4.8+6
  geolocator: ^5.3.1
  font_awesome_flutter: ^8.8.1
  flutter_modular: ^2.0.1
  rflutter_alert: ^1.0.3
  cloud_firestore: ^0.13.5
  firebase_messaging: ^6.0.15
  google_sign_in: ^4.4.6
  flutter:
    sdk: flutter

  firebase_storage: ^3.1.5
  firebase_auth: ^0.16.0
  cloud_firestore_all: ^0.1.1+4
 
  flutter_mobx: ^1.1.0
  mobx: ^1.2.1
  intl: ^0.16.1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.0
  build_runner: ^1.9.0
  mockito: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

scripts:
  mobx: flutter pub run build_runner build --delete-conflicting-outputs