name: MeuPedido
description: Meu Pedido Online integrador AGSystem.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  get: ^3.4.1
  meupedido_core:
    path: ../meupedido_core
  # image_picker_modern: ^0.4.12+3
  device_preview: ^0.4.5
  geolocator: ^5.3.1

  cielo_ecommerce: ^1.0.2
  # flutter_cielo: ^1.0.7
  mercadopago_sdk: ^1.1.3
  connectivity: ^0.4.8+5
  date_format: ^1.0.8
  image_cropper: ^1.2.2
  # image_gallery_saver: ^1.2.2
  # permission_handler: ^5.0.0+hotfix.5
  # crop: ^0.3.1+1
  firebase_messaging: ^6.0.13
  # flutter_masked_text: ^0.8.0
  masked_controller: ^1.0.1
  shared_preferences: ^0.5.7
  rflutter_alert: ^1.0.3
  # cache_image: ^1.0.5
  cached_network_image: ^2.2.0+1
  # firebase_image: ^0.1.5

  toast: ^0.1.5
 
  flutter_signin_button: ^1.0.0
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  google_sign_in: ^4.4.4
  #google_sign_in_web: ^0.8.2
  firebase_auth: ^0.16.0
  cloud_firestore_all: ^0.1.1+4
 
  flutter_mobx: ^1.1.0+1
  mobx: ^1.2.1+1
  flutter_modular: ^2.0.1
  
  flutter:
    sdk: flutter
  intl: ^0.16.1
  flutter_localizations:
    sdk: flutter

  dio: ^3.0.9
  font_awesome_flutter: ^8.8.1
  image_picker: ^0.6.6+1

  carousel_slider: ^2.1.0 

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  # effective_dart: ^1.2.1
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0
  flutter_native_splash: ^0.1.9
  # flutter_test:
  #   sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  image: assets/logoagsystem.png
  color: "42a5f5"
  # fill: true # imagem na tela inteira nao funciona em ios
  # android: false
  # ios: false
  android_disable_fullscreen: true
  # RODAR flutter pub pub run flutter_native_splash:create

scripts:
  mobx: flutter pub run build_runner build --delete-conflicting-outputs
  mobxw: flutter pub run build_runner watch
  buildapk: flutter build apk --split-per-abi
  buildapkarm: flutter build apk --target-platform android-arm
  celular: scrcpy --always-on-top